lines = [
    '@echo off\n',
    'setlocal EnableExtensions DisableDelayedExpansion\n',
    '\n',
    'set "REPO_URL=https://github.com/hanshendrickx/Medical-Signs-Complaints-Prompt.git"\n',
    'set "BRANCH=main"\n',
    '\n',
    'echo [INFO] Checking git repo...\n',
    'git rev-parse --is-inside-work-tree >nul 2>&1\n',
    'if errorlevel 1 (\n',
    '  echo [ERROR] Not a git repo. Run: git init\n',
    '  pause\n',
    '  exit /b 1\n',
    ')\n',
    '\n',
    'echo [INFO] Setting origin...\n',
    'git remote get-url origin >nul 2>&1\n',
    'if errorlevel 1 (\n',
    '  git remote add origin "%REPO_URL%"\n',
    ') else (\n',
    '  git remote set-url origin "%REPO_URL%"\n',
    ')\n',
    '\n',
    'set /p MSG=Commit message (Enter for auto): \n',
    'if "%MSG%"=="" set "MSG=Update %DATE% %TIME%"\n',
    '\n',
    'git add -A\n',
    'git diff --cached --quiet >nul 2>&1\n',
    'if errorlevel 1 (\n',
    '  git commit -m "%MSG%"\n',
    '  if errorlevel 1 ( echo [ERROR] Commit failed. & pause & exit /b 1 )\n',
    ') else (\n',
    '  echo [INFO] Nothing new to commit.\n',
    ')\n',
    '\n',
    'git push -u origin "%BRANCH%"\n',
    'if errorlevel 1 ( echo [ERROR] Push failed. & pause & exit /b 1 )\n',
    'echo [OK] Push complete to %REPO_URL%\n',
    'pause\n',
    'exit /b 0\n',
]
with open(r'c:\Users\hansh\MYSCC26\!PUSH.CMD', 'w', encoding='ascii') as f:
    f.writelines(lines)
print('Written OK')