# Generated by Django 6.0 on 2026-03-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familyuser",
            options={
                "permissions": [
                    ("view_family_data", "Can view medical data of family members"),
                    ("manage_children", "Can create and manage child accounts"),
                ]
            },
        ),
        migrations.AddField(
            model_name="familyuser",
            name="country",
            field=models.CharField(
                blank=True, help_text="ISO country code (e.g., US, DE)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When this temporary account expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="is_temporary",
            field=models.BooleanField(
                default=False, help_text="Guest account with expiry"
            ),
        ),
        migrations.AlterField(
            model_name="familymemberprofile",
            name="family_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.familygroup",
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="family_group",
            field=models.CharField(
                blank=True, help_text="Family name (optional)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent/guardian of this user (if minor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="is_family_admin",
            field=models.BooleanField(
                default=False, help_text="Can manage other family members"
            ),
        ),
        migrations.AlterField(
            model_name="familyuser",
            name="medical_consent_given",
            field=models.BooleanField(
                default=False, help_text="For minors: parental consent"
            ),
        ),
    ]
